server:
  port: 8999

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: LittleGarden
          uri: lb://LittleGarden
          predicates:
            - Path=/api/v1/auth/main/**
        - id: ContactUs
          uri: lb://ContactUs
          predicates:
            - Path=/contact/**